# Generated by Django 5.0.6 on 2024-05-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_book_category_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
