# Generated by Django 5.0.6 on 2024-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='banner',
            field=models.ImageField(blank=True, default='book_banners/default_banner.jpg', null=True, upload_to='book_banners/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='book_covers/default_cover.jpg', null=True, upload_to='book_covers/'),
        ),
    ]
